name: CI
on:
  pull_request: { branches: ["master"] }
  push: { branches: ["master"] }
  schedule: [cron: 0 0 * * 1]
  workflow_dispatch:
jobs:
  format-check:
    name: Format Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Format Check
        run: cargo fmt --check
  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      # Already avalible since it is listed in rust-toolchain.toml
      - name: Clippy
        run: cargo clippy -- -Dwarnings
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Nextest
        uses: taiki-e/install-action@v2
        with: { tool: nextest@0.9 }
      - name: Test
        run: cargo nextest run --profile ci
