name: Publish
on:
  release: { types: [published] }
jobs:
  publish:
    name: Publish (crates.io)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Publish
        run: cargo publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}